outputDirectory: /Users/mdml/GitHub/superdendrix-explorer/public/data
datasets:
  - name: 19Q1
    alterationsFileURL: https://www.dropbox.com/s/897qkrtcgfofoyk/depmap_19Q1_mutation_calls_oncoKB.tsv?dl=1
    samplesFileURL: https://www.dropbox.com/s/shtza7xyuji8s31/Q1_CERES_celllines.csv?dl=1
    dependenciesFileURL: https://www.dropbox.com/s/eesxw6h5l6lbfkz/gmm_20capped.tsv?dl=1
    twoComponentProfilesFileURL: https://www.dropbox.com/s/20aepmz387b5nst/list_of_2C_profiles.tsv?dl=1
